### ISSUE TITLE
Virtualization and transforms

### ISSUE THREAD

**Issue by 0xF013** [clauderic/dnd-kit#1003]
I am trying to marry dnd-kit with virtuoso and I am encountering an issue that is probably going to happy with any virtualization solution: if I am, say, in the middle of a long vertical list and tell a specific item to move to the top (without dragging), there is no animation of it going up since the element of the item is no longer in the DOM after it leaves the visible viewport. 

Is there a solution I missed and if not, is it maybe planned?

Thank you.

**Comment by clauderic** [comment]
Hey @0xF013, the recommended pattern is to use the `<DragOverlay>` component when working with virtualized lists. 

Once you have that set up, you can either:

- Hide the original sortable element while it is being dragged (for example, by setting its `opacity` or `visibility` to hidden)
- If you really want to keep a ghost of the element that is being dragged (similar to [this example](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-virtualized--basic-setup)), check if the virtualization library you are using supports "sticky" indices. Some virtualization libraries, like [react-tiny-virtual-list](https://github.com/clauderic/react-tiny-virtual-list) support passing an array of indices that should remain mounted at all times, which you can use to prevent the item being dragged from unmounting when it goes out of the viewport. If the library you are using does not support this feature, it should be relatively straightforward to open a PR with this feature, or you can always switch to a different library that supports it.

**Comment by withintheruins14** [comment]
I integrated virtualization with `<MultipleContainer />` in a layout like the [Many Items](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-multiple-containers--many-items) storybook example and am experiencing some screen jank when moving items from column to column - I think it's because rather than the previous column animating items into place (filling in the missing item) like it did before virtualization - with virtualization the previous column just rerenders and then items are moved. Does that make sense and might you know anyway to preserve that animation? @clauderic
