### ISSUE TITLE
Grid sort: the sortable box redraw when the box picked up

### ISSUE THREAD

**Issue by smurfs2549** [clauderic/dnd-kit#148]
For grid sort, I have 2x large box and 1x small box in the grid. All the boxes redraw when the sortable box picked up. The react-sortable-hoc package only sort and redraw when handleDragEnd. 
Sometimes, the box will blinking when drag over.

The screenshot:
https://user-images.githubusercontent.com/8286468/112081091-10647c00-8bbe-11eb-9421-e1e4954a44da.mp4
Code:
https://codesandbox.io/s/dndkit-sortable-image-grid-forked-j7ent?file=/src/App.jsx:1543-1557

**Comment by clauderic** [comment]
This is by design. By default, `DndContext` only measures droppable elements just-in-time right after dragging starts.

If you want to customize this behaviour, you can use the newly introduced `layoutMeasuring` prop of `DndContext` to measure nodes before dragging begins instead, which is available as of version `1.0.2` of `@dnd-kit/core`:

```tsx
import {LayoutMeasuringStrategy} from '@dnd-kit/core';

const layoutMeasuring = {
  strategy: LayoutMeasuringStrategy.BeforeDragging,
}

<DndContext layoutMeasuring={layoutMeasuring} />
```

**Comment by smurfs2549** [comment]
If I use version 1.0.2 of @dnd-kit/core, the LayoutMeasuringStrategy.BeforeDragging is undefind. When I upgrade to 1.2.0 of @dnd-kit/core, the page will not throw an undefind error.

After added 'layoutMeasuring', I can't drag sort any more.  
https://codesandbox.io/s/dndkit-sortable-image-grid-forked-j7ent?file=/src/App.jsx

**Comment by clauderic** [comment]
Remove the dependency `@dnd-kit/modifiers` in your sandbox. It is causing two versions of `@dnd-kit/core` to be used at the same time

**Comment by clauderic** [comment]
The issue is fixed if you upgrade `@dnd-kit/modifiers` to `^1.0.3`: https://codesandbox.io/s/dndkit-sortable-image-grid-forked-dz7ox

**Comment by clauderic** [comment]
Turns out this was actually an issue in CodeSandbox 😅   
https://github.com/codesandbox/codesandbox-client/pull/5609

**Comment by smurfs2549** [comment]
The boxes still redraw now, the react-sortable-hoc only redraw after sort end. Like the screenshot.
 @dnd-kit:
https://user-images.githubusercontent.com/8286468/112408109-2acf5e80-8d52-11eb-8759-c41db60e0493.mp4

react-sortable-hoc:
code: https://codesandbox.io/s/8y7n1r9y5j
https://user-images.githubusercontent.com/8286468/112408552-f7d99a80-8d52-11eb-81b8-5d910d701919.mp4

**Comment by clauderic** [comment]
This is most likely because you are moving items in `onSortOver` instead of only `onSortEnd`.

The layout of your grid is not predictable therefore you have to move items in the DOM to know what their next layout will be so you can smoothly transition to that new position using the FLIP technique.

There really is no magic solution here.

You need to make the layout of your grid predictable so that you can use a sorting strategy (or build a custom one yourself), in which case items will only move in the DOM `onSortEnd` so you won't see repaints while dragging (since only transform properties will be animated).

**Comment by smurfs2549** [comment]
yah, if U moving items in onDragEnd, the layout of the grid will no longer indicate where they will be placed. I want to make the grid can be predicted and don't want redraw while dragging.

**Comment by clauderic** [comment]
That's not possible with the built-in sorting strategies if `@dnd-kit/sortable`, they only work with layouts that are predictable.

You can try to build a custom sorting strategy strategy yourself to calculate the transforms needed to support your layout.

This is the only solution if you don't make your layout predictable and don't want to move items in `onDragOver`

**Comment by clauderic** [comment]
You can see the issue in this sandbox https://codesandbox.io/s/dndkit-sortable-image-grid-forked-t6393?file=/src/App.jsx

If you pass one of the built in sorting strategies (in this case, `rectSortingStrategy`) to SortableContext, since your layout is not predictable, the items shift position between the preview while dragging and where they end up on drop.

This is because the library is not able to guess what the final layout of the items is going to be.

**Comment by smurfs2549** [comment]
But how the react-sortable-hoc grid can be predicted and not redraw while draggling?
