### ISSUE TITLE
Items jumping in sortable single container when using a collection

### ISSUE THREAD

**Issue by steoo** [clauderic/dnd-kit#199]
Hi everyone, so the issue I'm seeing is the one I replicated here: https://codesandbox.io/s/hungry-maxwell-yrcrb?file=/src/App.js

You can see that when you move an object, it will return briefly to its original position and then will be moved to the final position. 

I noticed that the issue is that the IDs are calculated on the indexes of the collection – I also tried to create a separate IDs array, but that didn't really change the situation that much. 

Do you guys have any idea? It looks like the problem is some sort of race condition in the re-rendering of the thing :/

**Comment by clauderic** [comment]
Lots of issues with your code.

1. You need to pass stable keys to the `key` prop (you cannot use index as a `key`)
2. You cannot use `index` as an `id` for `useSortable` because it is not stable, for the same reason why you cannot use it as a `key`.
3. Your `handleDragEnd` logic was incorrect

https://codesandbox.io/s/mystifying-cray-w9ipm?file=/src/App.js
