### ISSUE TITLE
Rects on the `active` property should be typed as `ViewRect` instead of `LayoutRect`

### ISSUE THREAD

**Issue by dzcpy** [clauderic/dnd-kit#223]
When I use `console.log` to print `event.active.rect.current.initial`, there are `bottom, height, left, offsetLeft, offsetTop, right, top, width` 8 attributes. But in typescript its type `LayoutRect` has only `width, height, offsetLeft, offsetTop` 4 properties. So it's impossible to access the rest of properties without converting it to `any` first.

**Comment by dzcpy** [comment]
Also, there is a weird bug (or probably it's a feature?). When I `console.log` the entire event object, all `rect`s are `null`. JSON.stringify is the same. But if I `console.log(event.active.rect.current.initial)` I can get the actual value. I've spent hours figuring why it's null and finally found this 😢
Hopefully it's mentioned in documentation, so it can save others some time

**Comment by dzcpy** [comment]
By the way, here is my workaround:
```typescript

  interface LayoutRect {
    bottom: number;
    height: number;
    left: number;
    offsetLeft: number;
    offsetTop: number;
    right: number;
    top: number;
    width: number;
  }
  interface DragMoveEventFix {
    active: {
      data: DragMoveEvent['active']['data'];
      rect: {
        current: {
          initial: LayoutRect | null;
          translated: LayoutRect | null;
        };
      };
    };
  }

  const onDragMove = (event: Merge<DragMoveEvent, DragMoveEventFix>) => {
    // ...
  }
```

**Comment by clauderic** [comment]
>When I use console.log to print event.active.rect.current.initial, there are bottom, height, left, offsetLeft, offsetTop, right, top, width 8 attributes. But in typescript its type LayoutRect has only width, height, offsetLeft, offsetTop 4 properties. So it's impossible to access the rest of properties without converting it to any first.

This is indeed a mistyped property, it should be typed as `ViewRect` instead of `LayoutRect`. Feel free to open a PR, otherwise I'll get to this sometime today or tomorrrow.

> Also, there is a weird bug (or probably it's a feature?). When I console.log the entire event object, all rects are null. JSON.stringify is the same. But if I console.log(event.active.rect.current.initial) I can get the actual data. Kind of tricky. I've spent hours figuring why it's null and finally found this 😢
Hopefully it's mentioned in documentation, so it can save others some time

This isn't really a bug. On drag start, the `rects` of the `active` property have not been measured yet, because the `DragOverlay` for example is not mounted yet, so the `active.rect.current.initial` and `active.rect.current.translated` are both `null`.

When you use `console.log`, it logs a reference to the object, and since `rect` is a mutable ref, when you inspect the logged value, it changes between the time where you log it and the time where you inspect.
