### ISSUE TITLE
IE11 Polyfills

### ISSUE THREAD

**Issue by markkosorus** [clauderic/dnd-kit#271]
Recent 2.0.0 and 3.0.0 releases specify that:
```
If you need to support older browsers, include the appropriate polyfills in your project's build process.
```

Is there a list of what polyfills would be needed to make this work on IE11?

**Comment by clauderic** [comment]
Top of mind, you probably need `regenerator-runtime` and `String.prototype.includes`.

I don't have the exhaustive list, your best bet is probably to use something like `corejs` and [`browserlist` to specify the browsers that you support](https://github.com/clauderic/dnd-kit/blob/master/.browserslistrc) so that the polyfills are added for you by your build system

**Comment by tmeindle** [comment]
Just thought I would drop a comment here since I just set this library up for IE11 in my app.
When I do import {...} from '@dnd-kit/core' it includes the esm module and not the cjs file so I had to tell webpack to transpile it.

I used core-js/stable and regenerator-runtime.  Then I needed to add smoothscroll-polyfill for elem.scrollTo() and web-animations-js for elem.animate() since they are browser functionality polyfills and not included in core-js.
