### ISSUE TITLE
Sorting is not working when we use dnd/Sortable with antd table, also drag and drop is not smooth on mobile devices when we drag columns of antd table.

### ISSUE THREAD

**Issue by rajat-sf** [clauderic/dnd-kit#310]
Sorting is not working when we use dnd/Sortable with antd table, also drag and drop is not smooth on mobile devices when we drag columns of antd table.

Please find attached sandbox URL for your reference.
https://stackblitz.com/edit/react-wvyast?file=src%2FItem.js

Thanks in advance

**Comment by clauderic** [comment]
I didn't spend a lot of time on this, but it's definitely possible and as far as I can tell, everything is working fine with `@dnd-kit`.

Your sandbox doesn't work because the `Table` component from `ant-design` swallows the `style` property.

I edited your sandbox here with a slightly different approach that bypasses the issue https://stackblitz.com/edit/react-waoqzs?file=src%2FApp.js

**Comment by rajat-sf** [comment]
thank you @clauderic but somehow click handler for table column sorter is not called but listener for drag is called, 

would appreciate it if you can help us out resolve that.

**Comment by rohit-sourcefuse** [comment]
Following+

I am also facing this issue with antd. I have tried @clauderic solution, it works only one issue antd sorting not works.
I tried to fix this but did not get any solution.

**Comment by clauderic** [comment]
This isn't an issue with @dnd-kit. Please re-open an issue in the [ant-design repository](https://github.com/ant-design/ant-design/) or the [react-component/table repository](https://github.com/react-component/table) (which is what ant design uses under the hood to power its table component)

**Comment by CooCleC** [comment]
@rohit-sourcefuse @rajat-sf  https://stackblitz.com/edit/react-pdkml8?file=src/App.js  这个试一试
