### ISSUE TITLE
Moving to different sortable list triggers a reorder in original list

### ISSUE THREAD

**Issue by a6h-s** [clauderic/dnd-kit#345]
This is from the [Sortable / Multiple containers / Basic setup storybook](https://5fc05e08a4a65d0021ae0bf2-cbfrwoklyt.chromatic.com/?path=/story/presets-sortable-multiple-containers--basic-setup). When you move a card down to reorder the current list, then move it to another list, the original list will reorder again. Not sure what's causing this. 

I assume it's partly because the card doesn't actually move position in the DOM until onDragEnd. 

Also, this only happens the first time you move it to another list, it won't happen again during the same drag.

https://user-images.githubusercontent.com/26363886/123172662-ba81c780-d47d-11eb-8f42-2cde9bca6174.mp4

**Comment by davecoates** [comment]
This is because the droppable changes from the card (and so gets positioned after it) to the column (and so gets added to the start of the column). Easier to see if you highlight which droppable is being matched:


https://user-images.githubusercontent.com/1896376/127077757-589baf46-7e1e-41a8-b09c-1478f9be74cf.mov

**Comment by clauderic** [comment]
This is now fixed in the stories. This isn't something that can be fixed automagically for all consumers, it really depends on the use-case and collision detection strategy in use.

https://5fc05e08a4a65d0021ae0bf2-rvnnplhsjm.chromatic.com/?path=/story/presets-sortable-multiple-containers--basic-setup
