### ISSUE TITLE
Grid scrolling has errors.

### ISSUE THREAD

**Issue by linxianxi** [clauderic/dnd-kit#348]
When scrolling, it shows the wrong mouse position, and then the drag disappears.
![2](https://user-images.githubusercontent.com/47104575/123246672-a212bb00-d518-11eb-8389-284b3977cc91.gif)

**Comment by colepeters** [comment]
I'm experiencing the same issue. @clauderic is there any information I could provide to help solve this? (Also, I noticed this issue is tagged with 'needs reproduction case', however @doskarj's sandbox above reproduces the issue, so perhaps that might help?)

Thanks for all your work on this project, it's totally saved a project I'm working on. :)

**Comment by colepeters** [comment]
Solved it! In order to get to this work as it does in dnd-kit's demos ([see here for example](https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/story/presets-sortable-grid--scroll-container)), you need to use a DragOverlay which is rendered in a portal.

Check out [the example code for that story here](https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/story/presets-sortable-grid--scroll-container), along with [the documentation for the Drag Overlay](https://docs.dndkit.com/api-documentation/draggable/drag-overlay)).

By using a portalled Drag Overlay, I was able to get this to work perfectly! 🥳

**Comment by himanshuarya** [comment]
@colepeters @clauderic But this bug should be fixed without using a `DragOverlay` too. I am facing this issue as I am not using the `DragOverlay` in my code. I was able to reproduce this bug at the [Without Drag Overlay](https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/story/presets-sortable-grid--without-drag-overlay) example of Grid Sortable section. Below is the video for the same.

https://user-images.githubusercontent.com/16225398/153198699-508e70d7-b4b4-492e-89af-b6b5ca3d15f5.mp4

Notice when the auto-scroll happens how the mouse pointer moves far above the item which was moved.

**Comment by himanshuarya** [comment]
@colepeters @clauderic But this bug should be fixed without using a DragOverlay too. I am facing this issue as I am not using DragOverlay in my code. I was able to reproduce this bug at the [Without Drag Overlay](https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/story/presets-sortable-grid--without-drag-overlay) example of the Grid Sortable section. You will need to reduce the size of the window to enable a scroll to reproduce this bug. Below is the video for the same.

https://user-images.githubusercontent.com/16225398/153200253-097294e1-0952-4924-8e94-691d9d8b46f9.mp4

Notice when the auto-scroll happens how the mouse pointer moves far above the item which was moved.

Please let me know if any further information is required from my end.
Thanks!

**Comment by anki247** [comment]
Any update on this? Currently experiencing the exact same issue as posted by @himanshuarya 
BTW really nice lib 👍
