### ISSUE TITLE
[sandbox included] Error on drag across sortables

### ISSUE THREAD

**Issue by quacrobat** [clauderic/dnd-kit#353]
Hello, I ported the multi-select example from #13 in a sandbox here: https://codesandbox.io/s/autumn-currying-owjgm?file=/src/Selectable.js (use ctrl to multi-select)

I am getting **"Cannot read property 'offsetTop' of undefined"** whenever I try to drag items from a lower sortable to a higher one on the page. It works fine 90% of the time the other way around - but not always.
Why is **draggingRect** undefined sometimes?

**Comment by theMostCuriousHomunculus** [comment]
hey i ran into this issue as well trying to copy another example i had seen online.  my issue ended up being that the example i was copying from was using an earlier version of this library, and, since it is still in beta, the API had changed.  now from the event argument, you get active and over which each have a "rect" property.  there is no longer a "draggingRect" property of the event parameter.  so if you try to destructure off of it, it is undefined, which is fine, except when you then try to reference a property off of it (offsetTop), which only happens if you drag items a certain way (sometimes it fails and other times that line of the function is skipped because conditions aren't met).  hope this helps!
