### ISSUE TITLE
DragOverlay Wrapper does not resize to its content size.

### ISSUE THREAD

**Issue by clarknova** [clauderic/dnd-kit#367]
The DragOverlay Wrapper seems to have  the same size as the component that was used to start the drag and not the size of its content which messes up collison.

![image](https://user-images.githubusercontent.com/63824317/126290140-9fbd2f38-7934-4685-ba91-c6992c48811b.png)
For example: I want to drop it in the right dropzone but because of the overlay shape it has collision with the left dropzone.

**Comment by clauderic** [comment]
The DragOverlay wrapper is intentionally sized the same as the draggable source, and will remain that way even if its children are sized differently.

However, if you decide to resize the first child of DragOverlay, we will now use the collision rect of the child rather than the DragOverlay as of this commit: https://github.com/clauderic/dnd-kit/pull/337

This will be released in the next major version, however you can start using it right away by upgrading to the versions of `@dnd-kit` tagged with `@next` on npm
