### ISSUE TITLE
Nested onClick events inside <Draggable /> object

### ISSUE THREAD

**Issue by imikailoby** [clauderic/dnd-kit#381]
Hello there! Each click inside `<Draggable />` recognized as event to start drag object. How to prevert `onDragStart` event when I click nested elements with `onClick` handler?

Wrapper component example:
```jsx
const Draggable = (props: DndProps) => {
  const { id, children, data } = props;
  const { attributes, listeners, setNodeRef } = useDraggable({ id: id, data: data });

  return (
    <div ref={setNodeRef} {...listeners} {...attributes}>
      {children}
    </div>
  );
}
.... 

return (
// <DndContext ...>
//   <Droppable ...>
//   {array.map((element: ElementProps) => { ...
        <Draggable id={String(element.id)} key={i} data={element}>
          <Card content={element} />
        </Draggable>
/ /   }
//   <Droppable>
// <DndContext>
)
```

Card.tsx

```js

export const Card: React.FunctionComponent<Props> = React.memo((props: Props) => {
  const { content } = props;

  const handleClick = (e: React.MouseEvent<HTMLElement>) => {
    alert('click inside draggable component works! Yeah')
  }

  return (
    <div className='project-card'>
      <div>
        <p>Lorem ipsum...</p>
      </div>
      <button onClick={handleClick}>test nested OnClick action</button>
    </div>
  )
});

export default ProjectCard;

```

**Comment by clauderic** [comment]
The simplest solution to this problem would be to add [activation constraints](https://docs.dndkit.com/api-documentation/sensors/pointer#activation-constraints) to the sensor you are using, for example, by setting the `distance` constraint to a low value.

Alternatively, you can create your own sensor with a custom `activator` that returns `false` if the `event.target` is a button:

```tsx
class MyPointerSensor extends PointerSensor {
static activators = [
    {
      eventName: 'onPointerDown' as const,
      handler: (event) => {
        if (!event.nativeEvent.isPrimary || event.nativeEvent.button !== 0 || event.nativeEvent.target.tagName === 'BUTTON') {
          return false;
        }

        return true;
      },
    },
  ];
}
```

**Comment by imikailoby** [comment]
Thank you, @clauderic !

**Comment by amccloud** [comment]
@clauderic do you have a suggestion for when the entire draggable is clickable? I've tried pretty much every suggestion across a few threads and I'm close to concluding it is currently impossible with that specific combination

- The former example above doesn't work because the activation constraint doesn't prevent the nested event
- The later example above could work but my entire draggable element is clickable and draggable
- I've also tried listening to `isDragging` to prevent the interior click event, but the activation ends before the event click fires. This leaves `isDragging: false` in the nested onclick handler
- I've tried overriding `events.end = 'click'` but the way `MouseEvent` is currently constructed overrides any events I supply

Any tips or suggestions would be appreciated. Also happy to contribute a way to make this possible if it currently is not

**Comment by NachumTheWhale** [comment]
Why is this closed?

**Comment by linxianxi** [comment]
any update?
