### ISSUE TITLE
Unnecessary rerenders cause poor performance

### ISSUE THREAD

**Issue by srmagura** [clauderic/dnd-kit#389]
Our application has many droppable and draggable components displayed at once and is suffering from poor performance when dragging. When the dragged element crosses over a droppable, it causes all of our draggable and droppable components to rerender for seemingly no reason.

Here's a code sandbox that demonstrates the issue. Each `Draggable`/`Droppable` displays the number of times it has rendered. You'll notice that when dragging one of the red boxes, the render count of the other `Draggable` and `Droppable` components increases even though their props have not changed.

[Code Sandbox](https://codesandbox.io/s/dndkit-performance-x1b0v?file=/src/App.tsx)

The performance of the code sandbox is actually fine, but the unnecessary rerenders cause performance issues in our app because the draggables are expensive to rerender (something we could probably fix).

I'm not sure if this is expected behavior or a bug. If it does seem to be a fixable problem I would be happy to attempt a PR if you provide some direction.

P.S. Great library!

**Comment by uinz** [comment]
Nice Project!

This is caused by the react context mechanism

https://github.com/clauderic/dnd-kit/blob/master/packages/core/src/components/DndContext/DndContext.tsx#L629

I know there are several ways to avoid rerender

1. Further subdivide the context, honestly it is difficult
2. Use unstable API `readContext` or `useContextSelector`, avoid rerender through changeBits
3.Like redux, use context as an unchanging subpub center,
Use `forceUpdate` to notify the component update

**Comment by srmagura** [comment]
Great response! I was not able to find anything `readContext`. `useContextSelector` feels like the cleanest option to me. For reference, `useContextSelector` has a [userland implementation](https://github.com/dai-shi/use-context-selector) and and an [experimental PR in the React repository](https://github.com/facebook/react/pull/20646).

@clauderic, curious what your thoughts are on this. Would you accept a PR that added a dependency on the `use-context-selector` npm package? [Only 1 kb minified and gzipped](https://bundlephobia.com/package/use-context-selector@1.3.7)

The other option would be to keep `dndkit` as it is and rely on users to optimize their draggable and droppable components. Then when `useContextSelector` is (hopefully) added to React, we could update `dndkit` to use it.

**Comment by uinz** [comment]
@srmagura 
You can google `react + changeBits + readContext` 

```tsx
const currentDispatcher = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentDispatcher;

function readContext(Context, observedBits) {
  var dispatcher = currentDispatcher.current;
  if (dispatcher === null) {
    throw new Error('react-cache: read and preload may only be called from within a ' + "component's render. They are not supported in event handlers or " + 'lifecycle methods.');
  }
  return dispatcher.readContext(Context, observedBits);
}
```

**Comment by srmagura** [comment]
Just to set the record straight on this issue, I would like to implement a PR changing the library to use `use-context-selector` but I want approval from @clauderic or another maintainer before beginning the work. Thanks.

**Comment by clauderic** [comment]
@srmagura my preference would be to wait for React to officially support this feature. I'm open to changes that don't require bringing in additional dependencies.

We use `@dnd-kit` on some fairly large and complex applications at Shopify and have not run into any significant performance issues when the components that use `useDraggable`, `useDroppable` or `useSortable` and their child components are properly memoized.

You'd have to make a fairly strong case that bringing in this external dependency would drastically improve performance in ways that could not otherwise be achieved to convince me that this is worth doing now rather than waiting for first-class support for context selectors in React.

**Comment by srmagura** [comment]
Sounds good. I am pretty sure our issue can be addressed with proper memoization. 

Up to you if you want to keep this issue open for when React officially supports `useContextSelector` or if you want to close it.

**Comment by doflo-dfa** [comment]
@clauderic one thing we were noticed while using with react-window was the moment we used the useSortable hook in our memoized row component, it would re-render on scroll while not horribly expensive it was causing all of the rows to re-render which upon removing the call to useSortable that behavior ended.  We are still in search of a solution.

**Comment by clauderic** [comment]
This should mostly be resolved once https://github.com/clauderic/dnd-kit/pull/569 is shipped. It won't entirely prevent re-renders, but it will reduce un-necessary re-renders to the strict minimum.

**Comment by thngdude** [comment]
> #569

How did memoization work out for you? I've run into this issue and looking for options.

**Comment by srmagura** [comment]
Memoization solved the problem for me. My code looks something like this:

```jsx
const DraggablePresentation = React.memo(props => {
    // render the visible UI elements here
})

function Draggable(props) {
    const { setNodeRef, attributes, listeners } = useDraggable(...)

    return <div ref={setNodeRef} {...attributes} {...listeners}>
        <DraggablePresentation />
    </div>
}
```

**Comment by thngdude** [comment]
Thanks @srmagura 

I tried something similar with my code and memo, but it's not working as expected. Still getting hundreds of renders. Will look closer at your code.

**Comment by thngdude** [comment]
Got it working nicely. Thanks again @srmagura

**Comment by Dulanjala007** [comment]
this makes you need additional care to make things works properly. As react hooks meant to be used as is, needing to separate component into two separate components just because we need to add this dnd seems ridiculous. 
forking our own version seems the only solution for now.

**Comment by amirhmp** [comment]
Memoization only solve issues related to use cases that Draggable Component has complex UI to render. the main problem comes when we have many draggable components and by dragging one of them, all draggable items will rerender because useDraggable make them to rerender. i wish it was a mechanism to make useDraggable hook to returns only some part of the state. for example
```
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    state: { isDragging },
  } = useDraggable({
    id,
    data,
    pick: state => ({
      isDragging: state.isDragging,
    }),
  });
```
for example in my use case i have no need for "over", "node" or "active" so make UI rerenders because of this changes is redundant

**Comment by sandstone991** [comment]
> Thanks @srmagura @clauderic Memoization only solve issues related to use cases that Draggable Component has complex UI to render. the main problem comes when we have many draggable components and by dragging one of them, all draggable items will rerender because useDraggable make them to rerender. i wish it was a mechanism to make useDraggable hook to returns only some part of the state. for example
> 
> ```
>   const {
>     attributes,
>     listeners,
>     setNodeRef,
>     transform,
>     state: { isDragging },
>   } = useDraggable({
>     id,
>     data,
>     pick: state => ({
>       isDragging: state.isDragging,
>     }),
>   });
> ```
> 
> for example in my use case i have no need for "over", "node" or "active" so make UI rerenders because of this changes is redundant

I agree with this.

**Comment by osama-kwanso** [comment]
@srmagura Can you please do us a favor and send your code here? So we can get a a proper idea about your structure.

**Comment by nachozullo** [comment]
Having the same issue. When render more than 2500/3000 items, drag & drop behavior are slow (5s delay aprox.). I memoized item component, but delay still happens.

@srmagura did you try to implement `use-context-selector` library to reduce re-renders caused by context changes?  
I think it would be the best option. If you have been working in any branch I can give you a hand!

**Comment by uladsemenik** [comment]
There is a zero-dependency solution you could implement
https://github.com/dai-shi/use-context-selector/issues/109#issuecomment-1785147682

**Comment by pppdns** [comment]
> Memoization solved the problem for me. My code looks something like this:
> 
> const DraggablePresentation = React.memo(props => {
>     // render the visible UI elements here
> })
> 
> function Draggable(props) {
>     const { setNodeRef, attributes, listeners } = useDraggable(...)
> 
>     return <div ref={setNodeRef} {...attributes} {...listeners}>
>         <DraggablePresentation />
>     </div>
> }

I went with this approach too and it solved my performance issues completely

**Comment by nicubarbaros** [comment]
> Memoization solved the problem for me. My code looks something like this:
> 
> const DraggablePresentation = React.memo(props => {
>     // render the visible UI elements here
> })
> 
> function Draggable(props) {
>     const { setNodeRef, attributes, listeners } = useDraggable(...)
> 
>     return <div ref={setNodeRef} {...attributes} {...listeners}>
>         <DraggablePresentation />
>     </div>
> }

This one worked.
As well as avoid using `useDndContext` this one had the most performance issue for us.
