### ISSUE TITLE
Sortable Grid No Longer Updates After A Few Swaps

### ISSUE THREAD

**Issue by LuisOsta** [clauderic/dnd-kit#40]
**Issue**
Although both kinds of sensors work initially. After a certain number of moves, they stop working altogether. I've checked the event handler, and it never triggered. So I don't think it's an issue with the way I'm handling updates.

Any idea of what it could be? I've attached a [video](https://user-images.githubusercontent.com/18711855/103821510-e0342500-5033-11eb-9d71-983cb3d45004.mp4) in order to demonstrate the issue.

I followed this portion of the documentation in order to get started: https://docs.dndkit.com/presets/sortable
**Code**
```tsx
import { styled, Grid } from "@material-ui/core";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  DragEndEvent,
  TouchSensor,
} from "@dnd-kit/core";
import React, { useState } from "react";
import { SUQuestion } from "./QuestionCard";
import { questions } from "./square.data";
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
} from "@dnd-kit/sortable";

import { useSortable } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";

export const SquareUP = () => {
  const [currentQuestions, setQuestions] = useState(questions);
  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    }),
    useSensor(TouchSensor)
  );

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    const oldId = over ? over.id : "";
    if (active.id !== oldId) {
      setQuestions((oldQuestions) => {
        const oldIndex = oldQuestions.findIndex(
          (question) => question.letter === active.id
        );
        const newIndex = oldQuestions.findIndex(
          (question) => question.letter === oldId
        );
        return arrayMove(oldQuestions, oldIndex, newIndex);
      });
    }
  };

  const normalizedQuestions = currentQuestions.map(
    (question) => question.letter
  );
  return (
    <DndContext
      sensors={sensors}
      collisionDetection={closestCenter}
      onDragEnd={handleDragEnd}
    >
      <SortableContext items={normalizedQuestions}>
        <AssignmentContainer>
          <QuestionContainer>
            {currentQuestions.map((question, index) => {
              return (
                <Grid item xs={3} key={index}>
                  <SortableItem id={question.letter}>
                    <SUQuestion {...question} />
                  </SortableItem>
                </Grid>
              );
            })}
          </QuestionContainer>
        </AssignmentContainer>
      </SortableContext>
    </DndContext>
  );
};

const AssignmentContainer = styled("div")(({ theme }) => ({
  display: "flex",
  justifyContent: "center",
  border: "1px solid black",
  maxWidth: theme.spacing(100),
  borderRadius: theme.spacing(1),
}));

const QuestionContainer = styled((props) => <Grid container {...props} />)(
  ({ theme }) => ({
    margin: theme.spacing(2),
    width: "100%",
    justifyContent: "center",
  })
);


const SortableItem: React.FunctionComponent<{ id: string }> = ({
  children,
  id,
}) => {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
  } = useSortable({ id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    cursor: "pointer",
  };

  return (
    <div ref={setNodeRef} style={style} {...attributes} {...listeners}>
      {children}
    </div>
  );
};
```

**Comment by clauderic** [comment]
Here's a small sandbox you can look at that roughly replicates what I think you're trying to achieve, though I have abstracted complexity such as external dependencies: 
https://codesandbox.io/s/bitter-dawn-u4ll1?file=/src/App.js

**Couple of observations:**

- The `key` passed to the items in `map`  should be stable so that your components don't unmount and re-mount when the order changes: `<Grid item xs={3} key={index}>`. Use a stable `id` instead of `index`, since `index` is unstable.
- The [Pointer sensor](https://docs.dndkit.com/api-documentation/sensors/pointer) responds to [Pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events), which are emitted on touch devices. You should not be using the Pointer sensor in combination with the Touch sensor. Use either the Pointer sensor, or the Touch and Mouse sensors.

**Comment by LuisOsta** [comment]
Thanks for the help! You were completely right on the key property being the issue. Do you know why that would cause issues with the drag and drop?

And yeah sorry the inclusion of the other sensors was code that I'd forgotten to remove. Thanks!

**Comment by clauderic** [comment]
> Do you know why that would cause issues with the drag and drop?

I'm not entirely certain yet, this will require further investigation, but my best guess is that this is causing issues with draggable / droppable hook effects not properly running because they are not being cleaned up the in the way that would be expected (that is, using stable keys). 

Will investigate further, but going to go ahead and close this issue since using unstable keys is not a supported pattern.

**Comment by LuisOsta** [comment]
Sounds good, thanks!
