### ISSUE TITLE
Allow collision with drag overlay node rather than activeNode

### ISSUE THREAD

**Issue by wmain** [clauderic/dnd-kit#401]
In our application it's a frequent occurrence that things that can be dragged/sorted together are of different sizes. These sizes can differ radically and unpredictably and therefore make the dragging experience with a "presentational component" of the underlying node pretty bad. As an example, imagine dragging a giant rectangle from one container grid into a different container grid of many tiny squares. The large rectangle covers many of the squares during the drag, making it hard, from both the user's perspective and for the collision detection, to precisely drop where you want.

For this reason, and to provide additional contextual information about the thing being dragged, we've opted to go with a statically sized drag overlay that has no relation to the underlying node being dragging. It's small in size, contains an icon indicating what's being dragged, and the number of items that will ultimately be affected by the drag.

Our issue is that `DragOverlay` is sized based on the underlying node that started the drag. We can fix this stylistically by passing a style prop, but the `ViewRect` that is passed into collision detection is still from the underlying `activeNode`. This makes collision computation inaccurate in relation to what the user actually sees (our small, statically sized child of `DragOverlay`). 

I can see a few paths forward for making this experience better, but would love to get @clauderic's input here as, currently, `DragOverlay` seems fundamentally tied to the `activeNode` in many ways. Ultimately, the high-level goal is to allow collision to occur with drag overlay rather than the node the started the drag.

**Comment by clauderic** [comment]
Hey @wmain, thanks for the detailed issue.

I think you're describing the intended behavior, and in theory this should all be working as you're describing, though I'm also planning to add a ResizeObserver to the drag overlay contents in the near future to make this even more reliable. 

There's definitely a special relationship between the underlying node that started the drag (draggable source) and the drag overlay; this is by design as the library assumes that most consumers will want their drag overlay to be positioned at the coordinates of the draggable source, and potentially have the same dimensions.

Of course there will always be use-cases where you want to size the drag overlay differently than the draggable source. As you outlined, I believe this is already possible and fairly straightforward. In that scenario, the library defaults to the size of the first child of the DragOverlay component, assuming there is only a single child, see:
- https://github.com/clauderic/dnd-kit/blob/master/packages/core/src/utilities/nodes/getMeasurableNode.ts
- https://github.com/clauderic/dnd-kit/blob/master/packages/core/src/components/DndContext/DndContext.tsx#L231-L234

The collision rect is based on the dimensions of the measurable drag overlay node when the drag overlay is used: https://github.com/clauderic/dnd-kit/blob/master/packages/core/src/components/DndContext/DndContext.tsx#L264-L275

Is it possible that in your case, the DragOverlay component has more than a single child element?

**Comment by wmain** [comment]
@clauderic Thanks for the thorough response! I was definitely wrong in that the width/height of the collision rect is affected by the drag overlay node.

I did some additional investigation and I think that our potential issue is that modifiers don't apply to the collision rect. We're using the `snapToCenter` modifier that my teammate @trentmwillis shipped in order to center the drag overlay around the cursor and it feels to me like the modifier should affect the collision rectangle as well. Here's a demo gif demonstrating the core problem:

![collision](https://user-images.githubusercontent.com/5509303/128255502-ecda17a1-e8cd-401b-aee1-8bb9ad4d557e.gif)

As a legend, the drag overlay child is the black box with the "1 item" text; the drag overlay itself is the node with the blue background; and the collision rect is the red box. As you can see, there's a lack of proper attachment of the collision rect to the cursor, where the user will be expecting things to collide.

One potential path forward is to perform a similar transformation to the collision rectangle in the collision detection function that occurs in the modifier, but it feels to me like the expected behavior would be for modifiers to affect the collision rectangle as well.

**Comment by clauderic** [comment]
Just for further clarification, is the `snapToCenter` modifier applied to `<DndContext>` or `<DragOverlay>` in this scenario?

**Comment by wmain** [comment]
`DndContext` in this scenario.

**Comment by wmain** [comment]
@clauderic After looking at this more today I do think there needs to be a change to the underlying library in order to fix this. Not only does it feel correct to me for the collision rect to share position with the drag overlay, but because the collision detection function has access to neither the activator event, nor the width/height of the underlying node when using a drag overlay, there isn't really a workaround available in the collision detection function itself presently.

**Comment by clauderic** [comment]
Is this something you'd be comfortable taking a stab at @wmain? I remember looking at this a while back and I agree with you that this needs a bit of work, just haven't had time to prioritize this area yet.

**Comment by wmain** [comment]
Sure, happy to take a crack.

**Comment by juliushuck** [comment]
I had a similar problem - I have long rows in a datatable. When the user drags one or multiple, I want to show an overlay like x amount of people are being dragged. I also used snapCenterToCursor. For me, I needed two things:

1. I had to specify a fixed size for the drag overlay on the child inside DragOverlay or on the DragOverlay directly via style prop
2. I had to move snapCenterToCursor modifier to the DndContext because i previously had it on the DragOverlay
