### ISSUE TITLE
ScrollContainer does not work properly with useDragOverlay=false

### ISSUE THREAD

**Issue by filliperomero** [clauderic/dnd-kit#405]
As the title says, when using the ScrollContainer (which is one example that is in the code) with useDragOverlay equal a false, we have a problem in the dragging item, the item stop moving at some point (when we pass the view height set) but still change positions when I end the dragging.
The code of the example would end up like that:
```
export const ScrollContainer = () => (
  <div
    style={{
      height: '50vh',
      margin: '0 auto',
      overflow: 'auto',
    }}
  >
    <Sortable {...props} useDragOverlay={false} />
  </div>
);
```

The document says it is recomended to use the overlay but not mandatory. Maybe if it is needed, we should change de document?
Also, when we have the overlay, it's impossible to implement an onClick on the item. That is the reason I want to not use the overlay.

**Comment by clauderic** [comment]
> The document says it is recomended to use the overlay but not mandatory. Maybe if it is needed, we should change de document?
It's recommended (but not required) that you use the `<DragOverlay>` component when you have a scrollable list, because `@dnd-kit` already absolutely positions it for you. You'll need to manually set `position: fixed` on the draggable item yourself if you choose not to use the drag overlay. 

> Also, when we have the overlay, it's impossible to implement an onClick on the item. That is the reason I want to not use the overlay.

It's entirely possible to implement an `onClick` on the item while also using `<DragOverlay>`. There are many strategies you can use:

- Use a drag handle so that only the handle activates dragging, but not clicking on the item
- Set a small `distance` activation constraint on the sensor you are using
- Set a short `delay` activation constraint on the sensor you are using
