### ISSUE TITLE
The card cannot be put in an empty container

### ISSUE THREAD

**Issue by chenos** [clauderic/dnd-kit#432]
codesandbox

https://codesandbox.io/s/dnd-kit-multi-containers-forked-ndud1?file=/src/app.js

https://user-images.githubusercontent.com/2993310/130345966-31ccde3c-9855-4413-bc21-6dbc6ea1b9a3.mp4

**Comment by clauderic** [comment]
This is related to the collision detection strategy you are using (closest corners), because your containers are so tall, there are always other elements that are closer than the empty droppable container's corners.

You can try using the `rectIntersection` collision detection algorithm for example which should work better in this scenario https://codesandbox.io/s/dnd-kit-multi-containers-forked-qpzpz

Refer to https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms
