### ISSUE TITLE
Sortable elements with variable size looks weird when dargging an element

### ISSUE THREAD

**Issue by Thebarda** [clauderic/dnd-kit#44]
Hello !

I have an issue when moving an element through elements with variable. Indeed, the transform property applies a scale an X an Y axis on move elements.

Here is a repro project : https://codesandbox.io/s/test-dnd-kit-g4x2i

Is there a way to fix the translate properties an bypass the scale ones ?

Thank you in advance :)

**Comment by clauderic** [comment]
Hey @Thebarda, it's entirely up to the consumer to decide whether they want scale transformations or not.

Use `CSS.Translate.toString(transform)` instead of `CSS.Transform.toString(transform)`.

Will make a reminder to better document this.

**Comment by Thebarda** [comment]
I dived into the code and I found out the `Translate` property instead of `Transform` but the problem stil persist with `Translate`.

I tried to compute the translation myself by using properties provided by `useSortable` (over) but it doesn't provide information about the dragged element like `over` does

**Comment by clauderic** [comment]
Hey @Thebarda, the problem with your example is that none of the built-in sorting strategies will ever be able to predict and compute in advance the final positions of your items because their layout is not stable. 

For example, if you move `Codesandbox` after `it is very long` in this example:

<img width="209" alt="Screen Shot 2021-01-09 at 10 18 00 AM" src="https://user-images.githubusercontent.com/1416436/104095311-28398e80-5264-11eb-9b04-6ea39b3378a0.png">

The final result is actually:
<img width="215" alt="Screen Shot 2021-01-09 at 10 19 13 AM" src="https://user-images.githubusercontent.com/1416436/104095321-35ef1400-5264-11eb-8d88-64ad8270b0ad.png">

Which is not something that can easily be computed in advance without knowing a lot of information about the CSS layout of the parent container along with calculating the box models and margin collapsing of all the elements.

As a user, you have two options. The first and most technically challenging would be to write your own sorting strategy, based on the information you as the consumer know about your application to try and compute the transformations based on the box models and layout of the parent container. This would lead to the best user experience and most performant approach, but it's also fairly complex.

The other approach is to change the order of the elements dynamically in `onDragOver` and not use a sorting strategy at all, as per this example that I put together:
https://codesandbox.io/s/test-dnd-kit-forked-rhsq9?file=/src/App.js

It's not perfect, but it might do the job if you're not willing to invest time in the first approach.

**Comment by Thebarda** [comment]
That looks great for my use case. Sorry, I didn't know that sorting strategies was "optional". 
Yes you are right the first option is very complex (maybe gonna do it in a PR if have enough time) but the second option is good for now.

Thank you for the work done in this repo 👍

**Comment by clauderic** [comment]
The other alternative that I did not mention is to make the layout of your items predictable, which is probably the least effort / most performant, but may not align with the UX you are going for:

https://codesandbox.io/s/test-dnd-kit-forked-pun7j?file=/src/App.js

**Comment by Thebarda** [comment]
Yes, I thought about this solution but is not the best UX pattern.
Thanks about the given options

**Comment by chrisjpurdy** [comment]
For anyone that wants to use the example without any sorting strategy, you can fix the flickering issue with the following:
```
const debouncedDragOver = useCallback(
    debounce(handleDragOver, 100, {
      trailing: false,
      leading: true
    }),
    []
  );
```
Where `debounce` is from [lodash](https://lodash.com/). You can then just replace: 
`onDragOver={handleDragOver}` 
with
`onDragOver={debouncedDragOver}`

**Comment by arif1205** [comment]
> Hey @Thebarda, it's entirely up to the consumer to decide whether they want scale transformations or not.
> 
> Use `CSS.Translate.toString(transform)` instead of `CSS.Transform.toString(transform)`.
> 
> Will make a reminder to better document this.



> Hey @Thebarda, it's entirely up to the consumer to decide whether they want scale transformations or not.
> 
> Use `CSS.Translate.toString(transform)` instead of `CSS.Transform.toString(transform)`.
> 
> Will make a reminder to better document this.

Thanks man, It helps a lot.
