### ISSUE TITLE
Dragging doesn't work on touch devices with delay activation constraint and touch action auto

### ISSUE THREAD

**Issue by churichard** [clauderic/dnd-kit#453]
I'm writing a note-taking app with a sidebar of notes. You can click on a note to go to it, or you can press and hold in order to rearrange the note in the sidebar by dragging and dropping. Both of these actions happen on the entire note link (there's no separate drag indicator). Think of the way mobile Notion's sidebar works.

I'm using the Sortable preset with an activation constraint of `{delay: 250, tolerance: 5}`. I have touch action set to the default (auto). With this configuration, when I touch and hold a draggable, it gets "stuck" and cannot move anymore:

https://user-images.githubusercontent.com/4218237/132999415-1c84bae3-4464-4de2-a485-1107feab7ea3.mp4

If I have touch action set to none, then I am able to drag the draggable around, but the list doesn't scroll normally anymore.

I'm using Next.js, and sometimes I get the error `Uncaught TypeError: Cannot destructure property 'onCancel' of 'this.props' as it is undefined.` after this happens. This may be related to the problem.

**Edit: The same problem happens in stories like this one**, which is probably a simpler example to test: [Sortable > Virtualized > Basic Setup](https://5fc05e08a4a65d0021ae0bf2-ffprtowwny.chromatic.com/?path=/story/presets-sortable-virtualized--basic-setup)

It's impossible to scroll the actual container on a touch device. You can only drag and drop the items.

**Comment by clauderic** [comment]
Your use case is one where you would like to dynamically prevent scrolling. There's currently no way to make this work with the `PointerSensor` due to severe limitations in the [pointer events API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events). You can read more about those limitations here https://docs.dndkit.com/api-documentation/sensors/pointer#touch-action

However, it's possible to dynamically prevent the default browser behaviour of scrolling the page with `touchmove` event listeners. If you use the `TouchSensor`, everything should work as expected.

Up until now, there was a bug in iOS Safari that prevented this from working, but I just shipped a fix here: https://github.com/clauderic/dnd-kit/commit/1fe9b5c9d34237aae6ab22d54478c419d44a079a

Make sure you install the versions of `@dnd-kit` tagged with `@next` on npm to benefit from these changes. Refer to  https://github.com/clauderic/dnd-kit/pull/342#issuecomment-871842286 for more details.

**Comment by churichard** [comment]
Hey @clauderic! Thanks for the response.

I tried what you suggested (using `MouseSensor` and `TouchSensor` instead of `PointerSensor`), and it seemed to work fine when I was testing it using Dev Tools. However, I just tried it out on my Android device today and noticed that the dragging and dropping is inconsistent.

This is what I have set up:
```js
const sensors = useSensors(
    useSensor(MouseSensor, {
      activationConstraint: {
        distance: 10,
      },
    }),
    useSensor(TouchSensor, {
      activationConstraint: {
        delay: 250,
        tolerance: 5,
      },
    })
  );
```

I noticed that if I hold it for a short period of time and then start dragging, then the dragging works fine. However, if I hold it for a long time, then I feel my device vibrate and it gets stuck in place, like so:

https://user-images.githubusercontent.com/4218237/134080655-b48a1ef1-6f31-4340-ba9d-fb87dfa0c3af.mp4

And in Sentry, I get a `TypeError: Cannot destructure property 'onCancel' of 'this.props' as it is undefined.`, which I think points to here:
https://github.com/clauderic/dnd-kit/blob/1fe9b5c9d34237aae6ab22d54478c419d44a079a/packages/core/src/sensors/pointer/AbstractPointerSensor.ts#L217-L222

Perhaps `dnd-kit` is interacting weirdly with the native Android long press?

**Comment by clauderic** [comment]
Interesting, I'll have to test on one of my Android devices to see if I can replicate. Would you mind opening a separate issue for that?

As for the sentry error: Do you have an `onDragCancel` handler defined for your `<DndContext>`? It's possible there's a bug with the sensors if no onDragCancel handler is defined.

**Comment by churichard** [comment]
Thanks for the fast response, I really appreciate it! I just opened a new issue here: https://github.com/clauderic/dnd-kit/issues/458

I don't have an `onDragCancel` handler set up on my `DndContext` -- just `onDragStart` and `onDragEnd`.

**Comment by reshma-revi** [comment]
@churichard what's the fix for the touchsensor delay ?
