### ISSUE TITLE
@dnd-kit/modifiers package code seems incorrect.

### ISSUE THREAD

**Issue by virajsoni06** [clauderic/dnd-kit#466]
Hi @clauderic Saw the latest release has snapCenterToCursor. Nice one!
I've updated dnd-kit packages in my project. However they don't seem to work. Looked into the package and don't see any code from the master branch in it. This is what I see
![image](https://user-images.githubusercontent.com/13236286/135607803-9c591f42-3c17-4ab9-a9f4-12b45584b785.png)

Not sure how do I go about using this. Would appreciate some help, thanks.

**Comment by clauderic** [comment]
What do you mean by "they don't seem to work"?

The code for this modifier is here https://github.com/clauderic/dnd-kit/blob/master/packages/modifiers/src/index.ts#L7

If you updated to the latest version of `@dnd-kit/modifiers`, make sure you also upgrade all your other `@dnd-kit` packages too because there are breaking changes. Refer to the changelog of each package fo more details on the changes.
