### ISSUE TITLE
Is there a set date for when it will be production ready?

### ISSUE THREAD

**Issue by georgem1ke** [clauderic/dnd-kit#468]
Hi @clauderic ,

I wanted to use the library on a application for a client. The library does exactly what I need. 
However it's a big no-no for the client to have beta or pre-released libraries in a production environment.

I checked the issue #257, but it doesn't help with the fact that the library is on beta.

So my question is, if there is a set date to have the library production ready, not on beta?
I'd like to use this library, but I might have to use another one that is released for production if the client is strict with beta/pre-released libraries.

Kind regards,
Jorge M.

**Comment by clauderic** [comment]
There is no date set in stone for when the library will leave "beta" status. The main reason it is labeled as beta is because there are some use cases that are not well supported at the moment, and that there may be breaking changes in the future. However, the library follows semantic versioning, and there will be clear migration steps with each breaking change.

If the use case you're planning to build is similar to any of the examples on https://examples.dndkit.com, chances are that your use-case is well supported and production-ready.

Refer to https://github.com/clauderic/dnd-kit/discussions/418#discussioncomment-1209563 for more details
