### ISSUE TITLE
Sortable Items position is not updated sometimes when you start dragging an item and stay still on the first item you hover

### ISSUE THREAD

**Issue by AlexisIoannou** [clauderic/dnd-kit#470]
https://user-images.githubusercontent.com/16090746/136808379-c3d0cd65-38e2-4660-a2b8-b1a6d36165b0.mp4

I came across this issue and noticed that it also happens on the sortable tree example in storybook. It usually doesn't happens, but sometimes the dragged item will not push the bellow items downwards, and hide behind the hovered item

**Comment by moxxuk** [comment]
@clauderic have you seen this? I also think the title of the issue is not correct - you can drag a sortable quickly by more than one position, and the bug still occurs. Maybe 'Sortable Items position is not updated when moved too quickly after initial drag' or something like that?

**Comment by moxxuk** [comment]
The SortableContext component in the sortable package has this useEffect:
```
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      wasDragging.current = isDragging;
    }, 100);
```

Removing the timeout entirely and just using `wasDragging.current = isDragging;` got it working smoothly for me. What is the timeout for?

**Comment by combondrn** [comment]
I encountered this bug in two separate implementations of the Sortable preset: one vertical, one grid.  A fast grab-and-drag results in the dragged item apparently occupying the same index as the item being hovered.  After the dragged item is released, items visually re-order as expected.

It appeared after upgrading to the latest major releases.

Previous versions, without this behavior:
    "@dnd-kit/core": "^3.1.1",
    "@dnd-kit/modifiers": "^3.0.0",
    "@dnd-kit/sortable": "^4.0.0",

Versions with this behavior:
    "@dnd-kit/core": "^4.0.0",
    "@dnd-kit/modifiers": "^4.0.0",
    "@dnd-kit/sortable": "^5.0.0",

I have not identified which of the three results in the bug, but rolling all three back to the previous versions does cure the bug.  

As previous commenters noted, to re-create, the drag has to occur within a fraction of a second following the "grab".  Because of this speed required to re-create, I'd wager the activationConstraint settings most users employ effectively mask this bug.

**Comment by moxxuk** [comment]
@combondrn The `isDragging` state change only occurs upon activation, so unfortunately the activationConstraint does not mask the bug.

**Comment by HelKyle** [comment]
Same issue here, and I suddenly found if call force-update in `onDragOver` every time, the issue is gone~

```js
const [, forceUpdate] = useReducer(() => ({}), {});

const onDragOver = ({ active, over }: DragOverEvent) => {
    setTimeout(() => {
      forceUpdate()
    }, 100)
}
```
