### ISSUE TITLE
Elements opacity is not being reset with multiple Draggable elements

### ISSUE THREAD

**Issue by sscaff1** [clauderic/dnd-kit#53]
Here is a codesandbox with the issue. If you have a single Draggable element, then the default animation associated with DragOverlay works fine. If you have multiple Draggable elements then the animation associated with DragOverlay is broken. It looks like it never resets to the original opacity. Not sure why. 

https://codesandbox.io/s/intelligent-lake-uyimh?file=/src/App.js

Looks like these lines don't run https://github.com/clauderic/dnd-kit/blob/ae212fe3e756213d51edb2ba6c3a75869856d535/packages/core/src/components/DragOverlay/hooks/useDropAnimation.ts#L104-L106

Anyway around this? 

I mean you can get around this by setting the dropAnimation={null} in the DragOverlay (although that's not desired for my use-case).

**Comment by clauderic** [comment]
Hey @sscaff1, currently the `<DragOverlay>` component assumes that there are no more than one defined per `<DndContext>` provider. Try lifting the state up outside of your draggable components.

https://codesandbox.io/s/focused-thompson-5cxqv?file=/src/App.js

Having more than a single `<DragOverlay>` component _may_ be something that is supported in the future, but no immediate plans around this as use-cases seem limited.

I'm not familiar with the specifics of what the use-case you're building are, but my general advice would be that rendering the `<DragOverlay>` component _within_ the same component where you use `useDraggable` is not a good idea.

The rationale being that if your draggable component is reparented, the drop animation will not work since your draggable component will unmount and re-mount. Further, if your draggable component is unmounted while dragging, for example, if it is reparented `onDragOver`, the `<DragOverlay>` component will also unmount and re-mount, which could lead to unexpected results.

**Comment by sscaff1** [comment]
Thanks for explaining this. I want to render a different element depending in the DragOverlay on the type of the draggable. I'm guessing; however, I can just use `over` to do that.

**Comment by clauderic** [comment]
Gotcha. That's a fair use-case. 

For the time being, you'd need knowledge of what type of overlay the associated active draggable `id` is associated to. For now, you could do something like this: https://codesandbox.io/s/affectionate-carson-b9jif

In future versions of `@dnd-kit`, it will be possible to add metadata for your draggable elements to make this easier.

**Comment by brandonchinn178** [comment]
This bit me for the last hour. Any plans on supporting multiple DragOverlays? It would be nice for organization purposes to inline DragOverlays per Draggable. At the very least, perhaps this should be documented? I don't see anything [here](https://docs.dndkit.com/api-documentation/draggable/drag-overlay) mentioning you should only have one DragOverlay per context

Code sandbox showing differences in behavior with dropAnimation enabled/disabled and DragOverlay inside/outside map: https://codesandbox.io/p/sandbox/friendly-rgb-mkmpsg?workspaceId=80a4cde6-7ddd-4c6b-96b6-71c351c1c5e6
