### ISSUE TITLE
Question: Can sortable items render different sizes on drag start?

### ISSUE THREAD

**Issue by jquense** [clauderic/dnd-kit#544]
👋  thanks for awesome library, really enjoying it. A pattern that we'd to implement for sortable lists where the items are variable (sometimes long) heights in potential tall lists is to have items display as a smaller (maybe constant height) version of themselves when dragging starts. The question is whether this is possible with dndkit, and if so what hooks need to be used to make it happen. My initial attempts haven't being very fruitful because it appears that onDragStart is too late to change the shapes of items.

**Comment by HelKyle** [comment]
To better understand what problems you are facing, could you provide a CodeSandbox demo link?

**Comment by jquense** [comment]
Here is one, where the issue is likely the transition makes the initial measurement incorrect: https://codesandbox.io/s/dnd-kit-sortable-forked-zpfng?file=/src/Item.jsx

I am actually still trying to understand why i'm seeing worse behavior in our app vs the codesandbox, i think it's related to multiple containers, will investigate

**Comment by clauderic** [comment]
@jquense the problem with your example is the `transition`, @dnd-kit measures items right after dragging begins, but since you have a transition applied on the height changes, the height is incorrect at the point in time where it is measured.

As a temporary workaround, you can disable the height transition and it should work fine.

This is something I'm working on fixing in this PR https://github.com/clauderic/dnd-kit/pull/561

**Comment by clauderic** [comment]
This should now be fixed in the latest releases of @dnd-kit

**Comment by Akash187** [comment]
I think I am facing the same error. 

https://user-images.githubusercontent.com/21134455/214439627-1df84d83-198d-4f43-82a3-bf14cf22b9fb.mov
