### ISSUE TITLE
Multiple Containers onDragOver "infinite" loop when holding item between containers

### ISSUE THREAD

**Issue by KevinMusgrave** [clauderic/dnd-kit#552]
Thanks for this amazing package!

I've been trying out the [Multiple Containers demo](https://5fc05e08a4a65d0021ae0bf2-unebtvimdp.chromatic.com/?path=/story/presets-sortable-multiple-containers--basic-setup). I noticed that if I drag and hold an item halfway between containers for a few seconds, it gets stuck there for an additional few seconds after I let go of it. Here's a gif to illustrate:

![RMHEZ8NMQF](https://user-images.githubusercontent.com/2314891/147603643-f4039a34-f7c3-4101-ab6e-89c572d62022.gif)

With more complicated components, this can cause the entire page to die. 

I think the problem is repeated calls to [```onDragOver``` and ```setItems```](https://github.com/clauderic/dnd-kit/blob/1a897f7203eaef1d071f35d9747bfa7bdeb80059/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx#L288-L344).

Is there a way to fix this?

**Comment by clauderic** [comment]
The problem here is that the columns are pretty close to one another, and when an item is reparented from Column A to Column B, there's an infinite loop between the droppable rectangle that is closest to the draggable rectangle. 

This can be fixed by using the newly introduced `pointerWithin` collision detection algorithm instead, which is based on the coordinates of the pointer and will avoid these types of infinite loops.

This will be included in the next major release https://github.com/clauderic/dnd-kit/pull/557

See https://5fc05e08a4a65d0021ae0bf2-jjzxkknnls.chromatic.com/?path=/story/presets-sortable-multiple-containers--basic-setup which is based on this PR, which refactors the collision detection strategy of the multiple containers examples to use the `pointerWithin` algorithm #558

**Comment by KevinMusgrave** [comment]
Thanks for the quick fix!
