### ISSUE TITLE
Can i use this DND lib in NextJs or in any SSR ??

### ISSUE THREAD

**Issue by pradhuman01** [clauderic/dnd-kit#568]
If i can use in any SSR(eg. Nextjs, etc) then that would be great..

**Comment by clauderic** [comment]
It should work fine yes.

**Comment by pradhuman01** [comment]
It is ready for use in production Apps ?

**Comment by clauderic** [comment]
This project is in beta because there are currently some features that are not well supported. Having said that, this project is using semantic versioning, so major breaking changes will be identified and have clear migration steps outlined.

If the use case you're planning to build is similar to any of the examples on https://examples.dndkit.com, chances are that your use-case is well supported and production-ready.

We use @dnd-kit at scale at Shopify for millions of users, so you should feel fairly confident that it is a production-ready library.

**Comment by pradhuman01** [comment]
Thank You for your answer
