### ISSUE TITLE
Multi-drop animation broken after @dnd-kit/core@5.0.0

### ISSUE THREAD

**Issue by aeroheim** [clauderic/dnd-kit#582]
I use multi-select/drop extensively on a project and noticed a change in behavior in animations after upgrading to @dnd-kit/core@5.0.0 and related peer dependencies.

Reproducible behavior in [4.0.0](https://codesandbox.io/s/dnd-kit-animation-4-0-0-qk8is) (working) vs [5.0.0](https://codesandbox.io/s/dnd-kit-animation-5-0-0-sni6o) (missing animations).

Not sure if this is expected behavior after the changes in 5.0.0. I might've missed if there were any changes needed for migration - it's a bit hard to tell due to the multiple packages and different versions.

**Comment by clauderic** [comment]
Hey @aeroheim, to be honest I don't really understand your use case very well, but the main thing you need to provide to `useSortable` is a `getNewIndex` function, since you're using a non-standard way of sorting the array on drop.

It's a happy coincidence that there were layout animations in version 4.0.0, here's an updated sandbox where the drop animation works fine https://codesandbox.io/s/dnd-kit-animation-5-0-0-forked-xcghr
