### ISSUE TITLE
Role and tabIndex incorrect when disabled=true?

### ISSUE THREAD

**Issue by srmagura** [clauderic/dnd-kit#620]
Currently, if `disabled: true` is passed to `useDraggable`, the returned `attributes` still have `role: button` and `tabIndex: 0`. [My CodeSandbox](https://codesandbox.io/s/dnd-kit-disabled-role-shgjt?file=/src/App.tsx) demonstrates this. This is problematic for a few reasons:

- The user can tab to the draggable even though the element is not actually interactable. 
- `role="button"` may cause `cursor: pointer` to be applied to the draggable, even though it is not interactable. (This happens if using Bootstrap.)
- There is no indication to assistive technologies that the draggable is disabled.

I think it would be better if `role` was undefined and `tabIndex` was `-1` when the draggable is inactive.

**Comment by clauderic** [comment]
Thanks for the feedback. I've partially addressed your feedback in #751, but based on accessibility guidelines and best practices, the role should remain `role="button"` and the element should still be able to receive keyboard focus so that users that rely on assistive technologies can still tab and have the screen reader inform them that the draggable element is disabled.
