### ISSUE TITLE
Multiple containers, item is not triggering animation when dropped to another container

### ISSUE THREAD

**Issue by KatFishSnake** [clauderic/dnd-kit#695]
Hey guys, an amazing library you have built, many thanks for that. Im happy to see someone trying to challenge beautiful and react-dnd.

We are building a kanban board with your library and trying to figure out a few kinks. 

Codepen: https://codesandbox.io/s/dndkit-sortable-virtualized-image-grid-tlbdxt?file=/src/Pipelines.jsx

**Environment:** Codepen, Chrome v100, MacOS Monterey

**Steps to Reproduce:**
1. Start dragging an item from container A to container B
2. While dragging when item intersected the boundary of the container B, items in the container B jump giving space for the newly acquired item
 
**Expected:**
- Items in the container B animate to give space to the item being dragged in

**Actual:**
- Items in the container B jump away (without any animation) to give space to the item being dragged in

**Screens:**

https://user-images.githubusercontent.com/12003520/162588883-950b89fa-65ae-4895-a551-49103703122c.mov

**Comment by KatFishSnake** [comment]
@clauderic if you would have a minute can you please take a look at this, we would really appreciate your help

**Comment by clauderic** [comment]
@KatFishSnake This doe an issue with @dnd-kit, but rather a problem with react-virtualized (or how you are using react-virtualized). All of the items unmount and mount again when you insert a new item in the virtualized grid, which is why the layout animation isn't working.

Also you had the following code, which would also prevent any layout animations, even if the items were not unmounting and mounting again:

```ts
useSortable({
  animateLayoutChanges: () => false,
});
```
