### ISSUE TITLE
Sortable CSS transform bug on items with various width

### ISSUE THREAD

**Issue by daviedR** [clauderic/dnd-kit#737]
Hi,

I think there is a bug on Sortable's CSS `transform` when the sortable items have various width.

You can see the bug here: https://codesandbox.io/s/dazzling-kare-6gfutg

You can see the issue when swapping the position of `Search` and `Shopping Cart` items.

**Comment by clauderic** [comment]
I put this CodeSandbox together very quickly, but it illustrates how to achieve what you are attempting to do:
https://codesandbox.io/s/dnd-kit-page-builder-forked-vruvw1?file=/src/App.js

The problem with the example you posted above is that the layout is unpredictable. None of the built-in sorting strategies of @dnd-kit/sortable support unpredictable layouts.

The recommended approach in that situation is to move the items `onDragOver instead of `onDragEnd` and passing a sorting strategy that returns nothing to `SortableContext`:

```ts
function disableSortingStrategy() {
  return null;
}

<SortableContext strategy={disableSortingStrategy}>
```

Refer to this discussion for more a more detailed answer:

https://github.com/clauderic/dnd-kit/issues/44#issuecomment-757312037
