### ISSUE TITLE
Nesting of Nodes DOES NOT WORK

### ISSUE THREAD

**Issue by pachu4u** [clauderic/dnd-kit#75]
Hi,

I was in love with this library until i hit this issue. :( I hope you could help me get this resolved.

I have a node that is both draggable and droppable. 

I render two nodes into the playground like so

{nodes.map(node => {
          return <Node id={node.id} key={node.id} translate={node.deltaPos} />;
        })}

The issues with this approach.
1. Nodes do not drag smoothly - They flicker when we drag
2. The node 1 goes under node 2 when dragged over. Both have same z-index. Node 2 goes over node 1 correctly
3. The over property is null when node 2 is dropped over node 1. This is critical information to establish parent child relationship for nesting.
4. isOver from both Draggable and Droppable is not working as expected. They are false even when the node is dragged over.

Codesandbox - https://codesandbox.io/s/laughing-roentgen-6jopj

PS: In console log you can see the messages.

**Comment by clauderic** [comment]
I don't really understand your use-case well, but from what I understand, these are all issues related to not using the library correctly:

> Nodes do not drag smoothly - They flicker when we drag

This is because you added a transition on your nodes for `transform`:
```css
.node {
  transition: transform 250ms ease;
}
```

> The node 1 goes under node 2 when dragged over. Both have same z-index. Node 2 goes over node 1 correctly

The library does manage z-index for you, it's up to the consumer to manage z-index properly.

> The over property is null when node 2 is dropped over node 1. This is critical information to establish parent child relationship for nesting.
> isOver from both Draggable and Droppable is not working as expected. They are false even when the node is dragged over.

This is because you are rendering all of the contents of your `Background` component within a nested `<DndContext>` provider, so when you are dragging a `Node` component there are no other droppable areas within the context provider where those nodes are rendered, which explains why `over` is null.

**Comment by pachu4u** [comment]
Hi,

It does not work even if I remove the nested dnd-context. Over is still null.

Actually when I drop it, over is null. After dropping node 2 in node 1, if I just click on the handle without moving it. The over gets populated. It should definitely be a bug.
