### ISSUE TITLE
Sortable grid with different item sizes

### ISSUE THREAD

**Issue by sventschui** [clauderic/dnd-kit#77]
Hey

First thanks for the library, really appreciated!

Based on #41 I tried to create a sortable grid where the items have a different row/col span. I.e. one item is 2x1, another is 1x2 and a third is 1x1: https://codesandbox.io/s/dndkit-sortable-image-grid-forked-wmn92

I'm now facing two problems:
- When dragging an item over and item of different size (i.e. drag a 2x2 item over and item that is 1x1) the item will be resized. I tried to change `adjustScale` on the `DragOverlay` from true to false but couldn't figure out any change in behaviour.
- When dragging items so that a change in scroll behaviour occures (scroll -> no scroll) then there is a flickering and one is not able to correctly reorder. You can repro this by resizing the browser window in the CSB to approx. 900px height and then drag the show photo to the top left and then back to its original place.

Appreciate any pointers what I'm doing wrong/how to fix these problems.

**Comment by clauderic** [comment]
I think this is roughly what you're trying to build: https://codesandbox.io/s/dndkit-sortable-image-grid-forked-bjh7n?file=/src/App.jsx

That's the lowest effort solution, but it's also buggy, because the layout is shifting and the collision detection strategy can get into a state where it's constantly hesitating between two positions while the items are moved in the DOM.

Ideally for a use-case like this, you need to build a [custom sorting strategy](https://docs.dndkit.com/presets/sortable/sortable-context#strategy).

**Comment by sventschui** [comment]
Thanks for taking time to look into this issue, appreciated!

The sandbox already works a lot better. Unfortunately it crashes my chrome when dragging an item a bit longer. Any idea why this happens?

Implementing a custom sorting strategy would mean to check whether the element could be moved at the hovered place and move it there if it can be moved or move it to a later place in the sorted array otherwise, right? This sounds kinda difficult to me, especially as I am using a grid with a dynamic amount of columns (using `repeat(auto-fill, minmax(x, y))`). Do you have some pointers for me here?

**Comment by clauderic** [comment]
The stack overflow happens because the collision detection strategy can get into a state where it's constantly hesitating between two positions while the items are shifting positions in the DOM. Ideally the library should be able to detect that it's getting into such a scenario and avoid the stack overflow by picking one of the two positions, but this isn't currently planned; you'd need to try to open a PR for this yourself.

Indeed building a custom sorting strategy for your use-case would be extremely challenging, since you'd need to be able to compute the new positions of items.

**Comment by sventschui** [comment]
Thanks a lot for all the hints and your time. If I can come up with a solution I'll let you know. Closing the issue for now.

**Comment by justdvl** [comment]
Hello @clauderic  . Thanks for the Codesandbox example above, very helpful. 
Is there a way to not fill empty spot in a grid with other element, but leave it empty there? Let's say I changed your Codesandbox to only have 2 columns, so 1 row can have 2 items. I would like to allow user to take one item to other row and leave just 1 item in that row. If it is possible, how? Thanks.
@sventschui I am also experiencing a lot of flickering when collision detection strategy is undecisive. Did you manage to come up with a solution? I am not experienced enough to create PR myself, even though I would love to!
