### ISSUE TITLE
Scrolling while dragging creates an offset with dragged div and cursor

### ISSUE THREAD

**Issue by camachomarco** [clauderic/dnd-kit#783]
Hello @clauderic ,

Again, thanks for this library!

Here's an issue I haven't been able to solve. I am using Next.

When I grab an item and I drag it close the the limit of the screen, the screen scrolls (as it should) but the div get offset from the cursor while doing so... I'm not sure why, but I was able to recreate the issue in this sandbox: https://5lscly.sse.codesandbox.io/dashboard/library

You can edit the sandbox via this link: https://codesandbox.io/s/gallant-wozniak-5lscly?file=/src/components/FolderSubTile.js

*Make sure you navigate to "/dashboard/library" to access the grid.*

I'd like to eliminate that offset and make the cursor stay on the same point while dragging the div AND scrolling. The issue only happens when you scroll while dragging the div...

Also, here's a clip of the issue: 

https://user-images.githubusercontent.com/88408622/171493632-63164e6f-1164-44c7-834d-88ef7d34f19e.mp4

Does anyone know a solution to this?

Thanks! :)

**Comment by clauderic** [comment]
Hey @camachomarco, this issue only happens if you don't use the `<DragOverlay>` component. Also, this issue was fixed in the latest version of @dnd-kit. Make sure you upgrade to the latest version of `@dnd-kit/core` (and also upgrade all the @dnd-kit other packages since `@dnd-kit/core` is a dependency/peer dependency)
