### ISSUE TITLE
Multiple `DragOverlay`s with different modifiers within one DndContext

### ISSUE THREAD

**Issue by 4ndv** [clauderic/dnd-kit#818]
Hi! I'm in process of rewriting jQuery application to React, and it has multiple screens like this:

![изображение](https://user-images.githubusercontent.com/10115449/176362815-f4488eae-35c6-4784-95df-ea5b91baf983.png)

Categories is sortable and must be limited only to vertical axis. Items is also sortable, without axis limitations, and can be dragged to categories.

It's somewhat similar to #714, but items could be dragged only one way. Also I **really** want to keep "sidebar" and "items" parts separate from each other, because it is used in a lot of places within application. Can this be done without having one global DragOverlay?

**Comment by clauderic** [comment]
Currently, the best way to do this is to dynamically change what modifiers are active and what the `DragOverlay` renders based on the data of the active element.

You can leverage the `data` property of `useDraggable` and `useSortable` to store `modifiers` that should be applied when that type of draggable item is active, and also pass a component that should be rendered for the DragOverlay.

```ts
 function DraggableItem() {
  const {...} = useDraggable({
    id,
    data: {
      modifiers: [restrictToVerticalAxis],
      renderDragOverlay: ({active}) => <Item id={active.id} />,
    },
  });
}

function App() {
  const [active, setActive] = useState(null);

  return (
    <DndContext
      modifiers={active ? active.data.current.modifiers : []}
      onDragStart={({active}) => {
        setActive(active);
      }}
      onDragEnd={() => setActive(null)}
    >
      <DragOverlay>
        {active?.data.current?.renderDragOverlay?.(active)}
      </DragOverlay>
```

In the future, there will likely be new APIs introduced to facilitate configuring `<DndContext>` and rendering different types of `<DragOverlay>` children. However, I don't foresee it being possible to communicate across `<DndContext>` boundaries any time soon.

You can also use `useDndMonitor()` to manage state locally rather than having to manage state at the top level of your application where `<DndContext>` is rendered.

**Comment by 4ndv** [comment]
Thanks! Sounds just like what I need

**Comment by 4ndv** [comment]
Implemented that solution, works like a charm!

**Comment by nhatcuongboy** [comment]
hi @4ndv 
Can you show your code to me?
I am having a similar request
Thanks
