### ISSUE TITLE
Sorting is not working as expected with react-query

### ISSUE THREAD

**Issue by bjornhenriksson** [clauderic/dnd-kit#921]
Hey! Thanks for providing a fantastic library. I love it so far but we're running into some problems at work:

It seems like `dnd-kit` and specifically the sorting is not working as expected with `react-query`. I have [this example in a repo](https://github.com/bjornhenriksson/dnd-react-query-problem) where I am showcasing a sorting scenario where in one case I am setting the react-query cache directly (optimistic update) which causes the sorting to flicker. Seemingly you can "solve it" by setting any sort of random react state along side the cache update which makes me think that `dnd-kit` / or the sorting context is relying on the react state lifecycle to flush drop animations? Am I making the right assumption? And does that mean that `dnd-kit` does not work well with other stores except for react state? Are there any known workarounds to this flickering / inconsistency when using other data sources (such as `react-query` or Redux)?

## Example (flickering happens in the top example with the ❌ : 
https://user-images.githubusercontent.com/5759557/198110102-c07cebc1-14a3-45fc-831e-2fa4fc028aa4.mov

## Repo: https://github.com/bjornhenriksson/dnd-react-query-problem

Looking forward to solving this issue with you. Any tips and tricks are welcome!

**Comment by clauderic** [comment]
Hey @bjornhenriksson, I haven't used react-query much so I'm not exactly sure what the exact issue would be here, though I would imagine this is happening because of the async nature of the response that react-query returns, while @dnd-kit is expecting the component to update in the same batched state updates that are triggered in `onDragEnd`.

**Comment by reczy** [comment]
Hi @bjornhenriksson - It might not be what you're looking for, but have you tried performing the react query mutateAsync within dnd-kit's `cancelDrop`? That's what I ended up doing. 

The result is that the sortable item kinda pauses in place while you're waiting for the mutation promise to resolve (less abstractly - if the server is taking 2 seconds, then the sortable item will stay in place wherever you dropped it for those 2 seconds). Then, you can rely on `onDragEnd` if the react-query mutation was successful and you returned `false` in `cancelDrop` or `onDragCancel` if it wasn't and you returned `true`.

In case it's helpful, I just use react query's `onSuccess` of the mutation to `setQueryData` / `invalidateQueries` to manage updating items order on success. I also clone the items using `React.useState` in `onDragStart` and then revert back to that in `onDragCancel` if necessary.

As a final note, though maybe not relevant here, I do end up saving the initial react query (GET) results in an items object that I save with `React.useState` since I'm using multiple sortable containers and multiple initial react queries.

Sorry I don't have time to distill things into a sharable working example right now, but happy to answer any questions you have.

**Comment by bjornhenriksson** [comment]
Hey! Thanks for getting back to me @clauderic and @reczy ! 

> I would imagine this is happening because of the async nature of the response that react-query returns, while @dnd-kit is expecting the component to update in the same batched state updates that are triggered in `onDragEnd`.

This seems to indeed be the fact. More in depth it seems to be the fact that the sortable items that use `useSortable` refreshes it's state (and styling) whenever the drag end occurs before the parent component that holds the `react-query` state does (even if that one is close to instant when you use optimistic updates). I imagine this is not something we could work around in this library code itself since it's integral to support many real world scenarios that other people have and forcing a re-render of the parent might cause performance issues! Waiting for something async may also feel wonky for the end users. 

After some more research I'd imagine that this issue is fixed for a lot of devs by simply using a `DragOverlay` since the `onDragStart` and `onDragEnd` would use react state to keep track of the active index and therefor coincidentally fix the issue above. Like demonstrated here:

https://user-images.githubusercontent.com/5759557/198877154-c514e788-0818-4f0d-b85d-026142e6565d.mov

For my real world scenario I'll most likely end up working around the issue with another type of styling since my scenario needs to support both `react-query` for cross-app cache update, pagination and virtualized lists which introduces new issues where the active item might fall out of the currently rendered view etc. Spotify for instance handles DnD this way that puts less strain on instant UI changes:

https://user-images.githubusercontent.com/5759557/198877306-93138fdc-8b58-45a8-b752-8f1f832711e2.mov

In my example repo that could be something like this as well:

https://user-images.githubusercontent.com/5759557/198877465-57b8e185-deda-49e7-9eb9-0af32af57527.mov


## Conclusion
The above is not an issue with `dnd-kit`, more so based on the fact that `react-query` uses internal observers to manage it's cache that might not happen in the same render cycle as your state change. You can work around it in many different ways but most notably with `DragOverlay` and new styling if you're hellbent on only storing your state in `react-query`. If you're open to storing the optimistic update outside of `react-query` then you can just store and sync your optimistic update between react state and `react-query` by storing your query results in a state with `onSuccess` and optimistically put your client reorder directly into that state on drag end. You'll likely end up with two sources of truth in that scenario and you'll have to consider for yourself it that is something you can manage or not. 
Most often your issue could probably be fixed coincidentally by the `DragOverlay` state mentioned above.

Thanks again for a great versatile library @clauderic !

**Comment by mightym** [comment]
@bjornhenriksson I struggled with the same issue since days.
But then I came up with a very basic solution:
I'm basically passing my initial data from `useQuery` into a local state. 
Then after onDragEnd I just updated the sorted array in my state and in addition I mutate my remote data.

**Comment by dbousamra** [comment]
> @bjornhenriksson I struggled with the same issue since days. But then I came up with a very basic solution: I'm basically passing my initial data from `useQuery` into a local state. Then after onDragEnd I just updated the sorted array in my state and in addition I mutate my remote data.

@bjornhenriksson Beautiful mate. I was running into exact same issue, and was doing optimistic updates within the onMutate callbacks, setting the query key data manually. But i took your approach and just use local state, and then useEffect to update it anytime the queryCache changes. Works perfectly, and no flicker.

**Comment by alexnault** [comment]
I believe it's a similar issue to https://github.com/clauderic/dnd-kit/issues/833. dnd-kit works fine with local state but not so much with async state.

A solution would be for dnd-kit to wait for `onDragOver` to resolve before firing the drop animation.

**Comment by s33h0w** [comment]
This problem has been bothering me for two days. I’m really happy to see that someone encountered the same issue as I did and already found the solution! Thanks to @bjornhenriksson and @alexnault ! 

My situation is almost identical to what’s described here. I tried using `react-query` for optimistic updates in `onDragEnd`, and I noticed that the DragOverlay always returned to its original position instead of the dragged position. This made the dragging action feel laggy.

Based on the discussions here and #833 , I realized that this is likely due to the DragOverlay‘s render cycle happening one step ahead of the optimistic update’s render cycle. So I made the following changes, and the problem was solved! I hope this can help others!

```typescript
const DndContainer = () => {
  const [activeId, setActiveId] = useState<string | null>(null);
  const {mutateAsync: updateOrder} = useMutation();
  const onDragEnd = async () => {
    // setActiveId(null); // BEFORE
    await updateOrder();
    setActiveId(null);    // AFTER: Make activeId as null after optimistic update.
  }

  return (
    <DndContainer
      onDragEnd={onDragEnd}
    >
      {children}
      <DragOverlay>
        {activeId && <MyOverlay id={activeId} />}
      </DragOverlay>
    </DndContainer>
  );
}
```
