### ISSUE TITLE
Inconsistent multi-sort animations with virtualized lists

### ISSUE THREAD

**Issue by aeroheim** [clauderic/dnd-kit#96]
When re-ordering multiple items at once with virtualized lists, some of items fail to animate resulting in inconsistent animations.

Reproducible sandbox here: https://codesandbox.io/s/dnd-kit-multi-sort-animation-e8sxk?file=/src/App.js

The sandbox uses [react-window](https://www.npmjs.com/package/react-window) which is a fairly popular virtualization library. It is set to re-order multiple items on drag - if you compare the animations between the non-virtualized and virtualized lists there should be a noticeable difference in which items are animated. Not sure if this due to a bug or quirks with how react-window handles virtualization or if I'm forgetting something with the API.

P.S: Great work on the library! I've found it to be much cleaner and usable than a lot of the big alternatives out there - really appreciate all the work put into it!

**Comment by clauderic** [comment]
If i'm understanding the issue you're describing properly, the issue is that your items do not have stable keys. Seems like a small typo in your code, the prop for setting keys on your items is `itemKey`, not `itemKeys` (see https://react-window.now.sh/#/api/FixedSizeList)

<img width="416" alt="Screen Shot 2021-02-20 at 5 00 50 PM" src="https://user-images.githubusercontent.com/1416436/108609640-433c0a00-739d-11eb-9344-8807c7b8e980.png">

<img width="978" alt="Screen Shot 2021-02-20 at 5 01 09 PM" src="https://user-images.githubusercontent.com/1416436/108609643-4636fa80-739d-11eb-8365-b003f0d45db7.png">

https://codesandbox.io/s/dnd-kit-multi-sort-animation-forked-me7fo?file=/src/App.js
